"""add nidn to user

Revision ID: d119693ac480
Revises: f02db580f501
Create Date: 2025-04-01 19:00:57.247553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd119693ac480'
down_revision = 'f02db580f501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nidn', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint(None, ['nidn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nidn')

    # ### end Alembic commands ###
